= Transdata

image::https://raw.githubusercontent.com/CaliNetwork/TransData/main/artworks/logo.svg[]

The Integrated dashboard for cloud service, build for Hairpin Cloud Platform™

== Designs

> API Structure

[plantuml]
....
@startmindmap
* TransDataAPI
    *[#lime] Gateway
        *[#lightblue] Manage
            *[#lightblue] User
                *[#lightgreen] GetToken
                *[#lightgreen] Register
                *[#lightgreen] ResetPassword
            *[#lightblue] Order
                *[#lightgreen] PlaceOrder
                *[#lightgreen] CancelOrder
            *[#lightblue] Billing
                *[#lightgreen] PaymentGateway
            *[#lightblue] Ticket
                *[#lightgreen] ModifyTicket
            *[#lightblue] Service
                *[#lightblue] VM/<uuid>
                    *[#lightgreen] Reboot
                    *[#lightgreen] Shutdown
                    *[#lightgreen] Boot
                    *[#lightgreen] Rebuild<os>
                    *[#lightgreen] RequestRemoval
                *[#lightblue] PortForwarding/<uuid>
                    *[#lightgreen] Modify
                    *[#lightgreen] Delete
        *[#lightblue] Statics
            *[#lightgreen] GetUser
            *[#lightgreen] GetOrder
            *[#lightgreen] GetBilling
            *[#lightgreen] GetTicket
            *[#lightgreen] GetService

        *[#orange] AdminManage
            *[#orange] User
                *[#pink] ModifyUserObject
            *[#orange] Order
                *[#pink] ModifyOrderObject
            *[#orange] Billing
                *[#pink] SetBillingMethod
                *[#pink] ApplyRefund
                *[#pink] ModifyBillingObject
            *[#orange] Ticket
                *[#pink] ModifyTicketObject
            *[#orange] Cluster
                *[#pink] SetClusterToken
                *[#pink] RemoveCluster
                *[#pink] ModifyClusterObject
            *[#orange] Service
                *[#pink] ModifyServiceObject
                *[#pink] DeleteService
            *[#orange] ServiceTemplate
                *[#pink] ModifyServiceTemplateObject
                *[#pink] DeleteServiceTemplate
        *[#orange] AdminStatics
            *[#pink] GetUser
            *[#pink] GetOrder
            *[#pink] GetBillingStatics
            *[#pink] GetBilling
            *[#pink] GetTicket
            *[#pink] GetCluster
            *[#pink] GetClusterStatus
            *[#pink] GetService
            *[#pink] GetServiceStatus
@endmindmap
....

> Database model

[plantuml]
....
@startuml
object user {
    UserObject
}
object service {
    serviceObject
}
object billing {
    billingObject
}
object ticket {
    ticketObject
}
object order {
    orderObject
}
object settings {
    billingConfigure
    clusterConfigure
    siteConfigure
    serviceTemplate
}
@enduml
....

> Auth Model

[plantuml]
....
@startuml
start

if (user and password match) then (yes)
  #green:[AWAIT] Generate a token and write it into mongodb;
else (no)
  #pink:set status code 403;
endif
#lightblue:Return result;

stop
@enduml

@startuml
start

if (token is vaild) then (yes)
  #green:[AWAIT] Process Callback function;
else (no)
  #pink:set status code 403;
endif
#lightblue:Return result;

stop
@enduml
....